
name: Weekly HR News Build
on:
  schedule:
    # Monday 08:00 IST (IST=UTC+5:30 => 02:30 UTC)
    - cron: "30 2 * * 1"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scraper/run.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/
          git commit -m "Weekly data update" || echo "No changes"
          git push
